In [9]:
import pandas as pd
import csv
from sqlalchemy import create_engine

In [6]:

baharnmax = "baharnmax.csv"
baharnmax_db = pd.read_csv(baharnmax)

In [10]:
jack = "economyandcountry.csv"
jack_db = pd.read_csv(jack)

In [12]:
jack_db

                 countries  Population    GDP Climate
0             Afghanistan     31056997    700       1
1                 Albania      3581655   4500       3
2                 Algeria     32930091   6000       1
3                Anguilla        13477   8600       2
4       Antigua & Barbuda        69108  11000       2
5               Argentina     39921833  11200       3
6                 Armenia      2976372   3500       4
7                   Aruba        71891  28000       2
8               Australia     20264082  29000       1
9                 Austria      8192880  30000       3
10             Azerbaijan      7961619   3400       1
11           Bahamas, The       303770  16700       2
12                Bahrain       698585  16900       1
13             Bangladesh    147365352   1900       2
14               Barbados       279912  15700       2
15                Belarus     10293011   6100       4
16                Belgium     10379067  29100       3
17                 Belize       287730   4900       2
18                  Benin      7862944   1100       2
19                Bermuda        65773  36000       2
20                 Bhutan      2279723   1300       2
21                Bolivia      8989046   2400     1,5
22               Botswana      1639833   9000       1
23                 Brazil    188078227   7600       2
24     British Virgin Is.        23098  16000       2
25                 Brunei       379444  18600       2
26               Bulgaria      7385367   7600       3
27           Burkina Faso     13902972   1100       2
28                  Burma     47382633   1800       2
29                Burundi      8090068    600       2
..                     ...         ...    ...     ...
149                 Spain     40397842  22000       3
150             Sri Lanka     20222240   3700       2
151                 Sudan     41236378   1900       2
152              Suriname       439117   4000       2
153             Swaziland      1136334   4900     2,5
154                Sweden      9016596  26800       3
155           Switzerland      7523934  32700       3
156                 Syria     18881361   3300       1
157                Taiwan     23036087  23400       2
158            Tajikistan      7320815   1000       2
159              Thailand     64631595   7400       2
160                  Togo      5548702   1500       2
161                 Tonga       114689   2200       2
162     Trinidad & Tobago      1065842   9500       2
163               Tunisia     10175014   6900       3
164                Turkey     70413958   6700       3
165          Turkmenistan      5042920   5800       1
166                Uganda     28195754   1400       2
167               Ukraine     46710816   5400       3
168  United Arab Emirates      2602713  23200       1
169        United Kingdom     60609153  27700       3
170         United States    298444215  37800       3
171               Uruguay      3431932  12800       3
172            Uzbekistan     27307134   1700       1
173               Vanuatu       208869   2900       2
174             Venezuela     25730435   4800       2
175               Vietnam     84402966   2500       2
176                 Yemen     21456188    800       1
177                Zambia     11502010    800       2
178              Zimbabwe     12236805   1900       2

[179 rows x 4 columns]

In [13]:
baharnmax_db

,index,Country,Happiness_Score,Rates,Life Expectancy,HDI Rank,HumanDevelopmentIndex
0,0,Afghanistan,3.360,6.4,52.72,168,0.494
1,1,Albania,4.655,5.6,78.10,68,0.782
2,2,Algeria,6.355,3.3,76.50,85,0.753
3,3,Angola,3.866,8.9,60.00,147,0.577
4,4,Argentina,6.650,9.1,76.70,47,0.822
5,5,Armenia,4.360,5.7,74.90,83,0.749
6,6,Australia,7.313,11.7,82.30,3,0.938
7,7,Austria,7.119,11.4,81.40,20,0.906
8,8,Azerbaijan,5.291,2.6,73.30,80,0.757
9,9,Bahrain,6.218,5.7,79.10,43,0.846
10,10,Bangladesh,4.643,6.1,70.70,136,0.597
11,11,Belarus,5.802,21.4,71.30,53,0.805
12,12,Belgium,6.929,15.7,80.50,17,0.915
13,13,Belize,5.956,5.9,71.90,106,0.709
14,14,Benin,3.484,15.7,62.60,163,0.512
15,15,Bhutan,5.196,11.6,73.00,134,0.609
16,16,Botswana,3.974,11.5,60.13,101,0.712
17,17,Brazil,6.952,6.1,74.50,79,0.758
18,18,Bulgaria,4.217,7.9,74.90,51,0.810
19,19,Burundi,2.905,15.0,61.40,185,0.418
20,20,Cambodia,3.907,5.9,69.70,146,0.576
21,21,Cameroon,4.513,19.5,59.70,151,0.553
22,22,Canada,7.404,10.4,81.70,12,0.922
23,23,Chad,3.763,15.5,58.01,186,0.405
24,24,Chile,6.705,9.7,79.60,44,0.842
25,25,China,5.245,8.0,76.50,86,0.748
26,26,Colombia,6.481,7.0,78.20,90,0.747
27,27,Comoros,3.956,11.1,68.20,165,0.502
28,28,Croatia,5.488,11.5,77.80,46,0.828
29,29,Cyprus,5.546,4.5,81.90,32,0.867
...,...,...,...,...,...,...,...
87,87,Peru,5.743,5.1,79.70,89,0.748
88,88,Philippines,5.279,3.7,71.30,113,0.696
89,89,Poland,5.835,13.4,77.80,33,0.860
90,90,Portugal,5.123,8.6,80.90,41,0.845
91,91,Qatar,6.375,5.8,79.60,37,0.855
92,92,Romania,5.528,8.0,75.30,52,0.807
93,93,Rwanda,3.515,11.0,66.10,158,0.520
94,94,Senegal,4.219,11.8,65.60,164,0.499
95,95,Serbia,5.177,10.9,76.50,67,0.785
96,96,Singapore,6.739,7.9,82.10,9,0.930
97,97,Slovakia,6.078,10.1,77.80,38,0.853
98,98,Slovenia,5.768,13.3,81.00,25,0.894
99,99,Spain,6.361,6.1,82.70,26,0.889
100,100,Sudan,4.139,9.5,67.80,167,0.499
101,101,Suriname,6.269,23.2,72.20,100,0.719
102,102,Sweden,7.291,11.7,82.10,7,0.932
103,103,Switzerland,7.509,11.3,83.10,2,0.943
104,104,Tajikistan,4.996,3.3,72.90,127,0.647
105,105,Thailand,6.474,12.9,74.80,83,0.748
106,106,Togo,3.303,16.6,61.90,165,0.500
107,107,Tunisia,5.045,3.2,77.60,95,0.732
108,108,Turkey,5.389,7.2,79.30,64,0.787
109,109,Turkmenistan,5.658,7.2,70.40,108,0.705
110,110,Uganda,3.739,20.0,61.91,162,0.508
111,111,Ukraine,4.324,18.5,71.70,88,0.746
112,112,Uruguay,6.545,16.5,77.00,55,0.802
113,113,Uzbekistan,5.987,7.4,72.10,105,0.703
114,114,Yemen,3.724,9.8,64.92,178,0.462
115,115,Zambia,4.795,11.3,57.10,144,0.586
116,116,Zimbabwe,4.193,19.1,61.69,156,0.532